
services:
  - docker


before_deploy: pip install docker-compose

after_deploy:
  - docker-compose run --rm user-api-test
=======
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest