"""create address table

Revision ID: 2b29fb165621
Revises: 4f9bace0c0e2
Create Date: 2021-09-20 17:09:19.976231

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.enums import IntEnum, State

# revision identifiers, used by Alembic.
revision = '2b29fb165621'
down_revision = '4f9bace0c0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
                    sa.Column('id', postgresql.UUID(as_uuid=True),
                              server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('street', sa.String(),
                              nullable=False, index=True),
                    sa.Column('apartment_number',
                              sa.Integer(), nullable=False),
                    sa.Column('state', IntEnum(State), nullable=False),
                    sa.Column('zip_code', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('street', 'apartment_number',
                                        name='address_street_apartment_number_key')
                    )
    op.create_index(op.f('ix_address_state'),
                    'address', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_state'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
