"""address id foreign key in users

Revision ID: 365161f1abd3
Revises: 2b29fb165621
Create Date: 2021-09-20 17:11:04.132128

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '365161f1abd3'
down_revision = '2b29fb165621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key('users_address_id_fkey', 'users', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_address_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###
