"""create user table

Revision ID: 4f9bace0c0e2
Revises: 
Create Date: 2021-09-20 17:02:27.748021

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.enums import Degree, Gender, IntEnum

# revision identifiers, used by Alembic.
revision = '4f9bace0c0e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.create_table('users',
                    sa.Column('id', postgresql.UUID(as_uuid=True),
                              server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('user_name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('degree', IntEnum(Degree), nullable=False),
                    sa.Column('gender', IntEnum(Gender), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('first_name', 'last_name', 'age', 'email',
                                        name='users_first_name_last_name_age_email_key')
                    )
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=False)
    op.create_index(op.f('ix_users_degree'), 'users', ['degree'], unique=False)
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_index(op.f('ix_users_degree'), table_name='users')
    op.drop_index(op.f('ix_users_age'), table_name='users')
    op.drop_table('users')
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp";')
    # ### end Alembic commands ###
