"""Add stakeholders table

Revision ID: 69c134b023ae
Revises: 78571db4bf04
Create Date: 2021-10-05 09:46:22.499747

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69c134b023ae'
down_revision = '78571db4bf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholders',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('created_by_email', sa.String(), nullable=True),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_index(op.f('ix_stakeholders_is_admin'),
                    'stakeholders', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stakeholders_is_admin'), table_name='stakeholders')
    op.drop_table('stakeholders')
    # ### end Alembic commands ###
