"""drop index street

Revision ID: 78571db4bf04
Revises: 365161f1abd3
Create Date: 2021-10-05 09:32:42.838905

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '78571db4bf04'
down_revision = '365161f1abd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_address_street', table_name='address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_address_street', 'address', ['street'], unique=False)
    # ### end Alembic commands ###
