"""Add created_by_email users table

Revision ID: c058d7c002fd
Revises: 69c134b023ae
Create Date: 2021-10-05 09:47:22.406254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c058d7c002fd'
down_revision = '69c134b023ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_by_email')
    # ### end Alembic commands ###
